# Generated by Django 6.0 on 2026-01-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_department_user_purse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purse_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
